package ligo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.AbstractButton;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.*;
import java.awt.image.BufferedImage;
import java.io.Console;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;
import ligo.JP_LIGO;
import ligo.JP_BLACKHOLES;
import ligo.JP_EINSTEIN;
import ligo.JP_DISCOVERY;

/**
 *
 * @author Kyle
 */
public class Main_Menu extends javax.swing.JFrame {

    private static JPanel pnl = new JPanel();
    private static JPanel intro_panel = new JPanel();
    private static int current_panel = 0;
    private static JButton btn_prev = new JButton("Prev");
    private static JButton btn_next = new JButton("Next");
    private static JPanel[] panels = new JPanel[5];
    
    public Main_Menu() throws IOException {
        
        this.setTitle("LIGO");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(0,0,screenSize.width, screenSize.height);  
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setLocationRelativeTo(null);
	this.setDefaultCloseOperation(EXIT_ON_CLOSE);
	this.setVisible(true);
        this.setLayout(new BorderLayout());
        
        JLabel background = new JLabel(new ImageIcon (
                "C:\\\\Users\\\\Kyle\\\\Desktop\\\\LSU\\\\2016Spring\\\\CSC4243\\\\LIGOswing\\\\LIGO\\\\images\\\\space.jpg"));
        this.setContentPane(background);
        background.setLayout(new FlowLayout());
        
        pnl.setPreferredSize(new Dimension(screenSize.width, screenSize.height));
        //pnl.setPreferredSize(new Dimension(screenSize.width-200, screenSize.height-250));
        //pnl.setBackground(Color.black);
        //pnl.setBorder(BorderFactory.createLineBorder(Color.gray));
        pnl.setOpaque(false);
        
        btn_prev.setActionCommand("enable");
        btn_prev.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int temp = (checkPanel("prev", current_panel));
                current_panel = temp;
                JPanel tempPanel = panels[temp];
                pnl.setVisible(false);
                pnl.remove(1);      
                tempPanel.setPreferredSize(new Dimension(screenSize.width-200, screenSize.height-250));
                pnl.add(tempPanel, 1);
                pnl.setVisible(true); 
            }
        });
       
        //btn_next.setActionCommand("enable");
        btn_next.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int temp = (checkPanel("next", current_panel));
                current_panel = temp;
                JPanel tempPanel = panels[temp];
                pnl.setVisible(false);
                pnl.remove(1);
                tempPanel.setPreferredSize(new Dimension(screenSize.width-200, screenSize.height-250));
                pnl.add(tempPanel, 1);
                pnl.setVisible(true); 
            }
        });
        
        intro_panel.setPreferredSize(new Dimension(screenSize.width-200, screenSize.height-250));
        intro_panel.setBackground(Color.yellow);
        pnl.add(btn_prev,BorderLayout.WEST);
        pnl.add(intro_panel,BorderLayout.CENTER);
        pnl.add(btn_next,BorderLayout.EAST);
        background.add(pnl);
        
        this.add(pnl, BorderLayout.CENTER);
        this.pack();
        this.setVisible(true);      
   
        //JP_LIGO jp_ligo = new JP_LIGO();
        panels[0] = intro_panel;
        panels[1] = new JP_LIGO();
        panels[2] = new JP_BLACKHOLES();
        panels[3] = new JP_EINSTEIN();
        panels[4] = new JP_DISCOVERY();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1374, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }
    
    public static int checkPanel(String btn, int currentPanel){
        
        int newPanel = 0;
        
        if("prev".equals(btn)){
           if(currentPanel == 0){
               newPanel = 4;
           }else{
               newPanel = currentPanel - 1;
           }
        }
        else{
            if(currentPanel == 4){
               newPanel = 0;
           }else{
               newPanel = currentPanel + 1;
           }
        }
        
        return newPanel;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}